services:
  - type: web
    name: phytobot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PLANTID_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: VECTOR_DB_PATH
        value: ./vector_db
